language: android
sudo: true
jdk:
    - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra
env:
  -  TERM=dumb
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build