language: android
sudo: true

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra

env:
  -  TERM=dumb

script:
  - ./gradlew build